version: '2'
services:
    nginx:
      build: ../images/nginx
      ports:
        - "8080:80"
      links:
        - php
      volumes:
        - ../../:/php_sandbox

    php:
      user: "1000:33"
      build: ../images/php
      links:
        - mysql
      volumes:
        - ../../:/php_sandbox
      working_dir: /php_sandbox
      extra_hosts:
        - "host.docker.internal:host-gateway"

    mysql:
      user: "999:999"
      image: mysql:8.0.40
      environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=1
        - MYSQL_DATABASE=php_sandbox
        - MYSQL_USER=php_sandbox
        - MYSQL_PASSWORD=password
      volumes:
        - ../../var/mysql_data:/var/lib/mysql
      ports:
        - "8060:3306"
